apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: statusquarkusio-hps4
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-iina-tenant/status-quarkus-io/statusquarkusio-hps4@sha256:85bb1544752daeecfd2202b6ca4e7b18c25197da8ea6a7cf89447d8678affd93
        name: my-java-quarkus
        resources: {}
status: {}
