apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-hps4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-hps4
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-hps4
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-hps4
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-hps4
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-iina-tenant/status-quarkus-io/statusquarkusio-hps4@sha256:85bb1544752daeecfd2202b6ca4e7b18c25197da8ea6a7cf89447d8678affd93
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
